ml-explore/mlx-data

setup.py
Since CMake is now a python installation dependency, there is no need to remove pip-build-env from the python path.
=> Remove old cmake fix

docs/src/python/common_datasets.rst, python/mlx/data/datasets/__init__.py, python/mlx/data/datasets/speechcommands.py
This PR adds the Speech Commands (v0.02) dataset. I've used the existing `librispeech` implementation as a reference for the dataset, reading directly from the tar archive!
While an example for an audio dataset already exists (`librispeech`), I feel Speech Commands is a popular dataset that's also often used as a proof of concept by the speech/audio community, and might be handy for people taking `mlx-data` for a spin considering the small footprint (~2 GB).
=> An implementation of the Speech Commands (v0.02) dataset

mlx/data/core/image/ImageTransform.cpp
=> throw on bad image type to avoid silent failures

mlx/data/buffer/FromVector.cpp, python/src/wrap_buffer.cpp, python/tests/test_buffer.py
The __getitem__ method now accepts both positive and negative indices. Overflow issues are appropriately handled as out_of_range/IndexError, maintaining consistency with mx.array and other containers.
Additionally, an initial Python unit test has been included to kickstart the testing process.
Closes #18
Running tests from circleci is still missing, but that is hard to do from a fork (at least I don't know how). I personally just have experience with GH workflows.
=> support negative indexing of buffers

benchmarks/comparative/librispeech/mlx_data.py, python/mlx/data/__init__.py
The comment in the fix explains it all. Basically for some static builds there is a bus error if numpy is not imported and pybind11 has to cast to numpy.
=> Fix benchmark and occasional bus error

super/CMakeLists.txt
Now built with CMake, such that CMake-based packages found it properly.
=> super build: fix ogg dependency

docs/src/python/common_datasets.rst, python/mlx/data/datasets/__init__.py, python/mlx/data/datasets/mnist.py
This adds Fashion-MNIST, which is a drop-in replacement for the original MNIST dataset.
=> Add Fashion-MNIST dataset

mlx/data/core/ThreadController.cpp, python/mlx/data/__init__.py
found while tracking down openblas-related invalid read -- updated comment in that respect.
=> missing dlclose()

mlx/data/core/Tokenizer.cpp
Previously the following code would fail to tokenize the 2nd string even though `ignore_unk` is set to True.
```python
import mlx.data.core
from mlx.data.core import CharTrie
if __name__ == "__main__":
vocab = CharTrie()
vocab.insert("hello")
vocab.insert(" world")
tokenizer = mlx.data.core.Tokenizer(vocab, ignore_unk=True)
print(tokenizer.tokenize_shortest("hello world"))
print(tokenizer.tokenize_shortest("hello "))
```
=> Fix an edge case tokenizing with ignore unknown

mlx/data/core/AWSFileFetcher.cpp, mlx/data/core/AWSFileFetcher.h, mlx/data/core/FileFetcher.cpp, mlx/data/core/FileFetcher.h, python/src/wrap_core.cpp
- AWSFileFetcher will not download a file already present on local disk
- FileFetcher::erase(filename) erases filename from the cache / local disk
- AWSFileFetcher::update_credentials() updates the AWS S3 client with provided credentials
- AWSFileFetcher::update_credentials_with_callback() allows to update credentials via a callback...
- when credentials are outdated
- every given period of time
=> Improves AWSFileFetcher

python/mlx/data/datasets/cifar.py
Simply added `import common.Path` at cifar.py file.
Got an error while following [CIFAR10 example](https://github.com/ml-explore/mlx-examples/tree/main/cifar) and just adding import fixed it.
```
$ (.mlx) ~/MLX/ python CIFAR
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/Users/junnos/MLX/CIFAR/__main__.py", line 67, in <module>
main(args)
File "/Users/junnos/MLX/CIFAR/__main__.py", line 35, in main
datas: tuple[Stream, Stream] = get_cifar10(
^^^^^^^^^^^^
File "/Users/junnos/MLX/CIFAR/dataset.py", line 9, in get_cifar10
trainset: Buffer = load_cifar10(root=root, train=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/junnos/MLX/.mlx/lib/python3.12/site-packages/mlx/data/datasets/cifar.py", …
```
=> Add `Path` import to cifar file

python/mlx/data/__init__.py
Support the case of 
```
import mlx.data as dx
dx.tokenizer_helpers.xxx
```
=> Make tokenizer_helpers being imported

docs/src/hf_datasets_streams.rst, docs/src/index.rst
Hello, I added a step by step on how to use the `datasets` library from Hugging Face and turn that into `mlx streams`
Although mlx is not dependent on hf, it is such a common workflow in the industry that I thought it might be helpful to share. Not sure if this should sit in mlx-data or the main mlx repo.
I also got a notebook version here https://github.com/mwrites/apple-mlx-tutorials/blob/main/hf_datasets_mlx_streams.ipynb
I noticed that these two minimal examples
```python
buff = dx.buffer_from_vector([{"x": i} for i in range(10)])
print(type(buff[0]['x']))
buff = buff.key_transform("x", lambda x: mx.ones(3), output_key="o")
print(type(buff[0]['x']))
```
always print `<class 'numpy.ndarray'>` hence the need to do `mx.array(buff[0]['x'])` again later when passing the inputs to a model.
=> doc - added walkthrough for using huggingface datasets with mlx streams

CMakeLists.txt, benchmarks/comparative/caltech101/mlx_data.py, benchmarks/utils.py, docs/src/buffers_streams_samples.rst, docs/src/conf.py, docs/src/hf_datasets_streams.rst, docs/src/python/buffer.rst, mlx/data/Buffer.cpp, mlx/data/Buffer.h, mlx/data/stream/OrderedPrefetch.cpp, mlx/data/stream/OrderedPrefetch.h, python/src/wrap_buffer.cpp, python/src/wrap_stream.cpp, python/tests/test_buffer.py
Here is a possible implementation of the `Buffer.ordered_prefetch` method.
The `OrderedPrefetch` is a `Stream` produced by prefetching in parallel (using a `ThreadPool`) contiguous elements from a `Buffer`. The implementation is an hybrid between `Buffer.to_stream` and `Stream.prefetch`.
`Prefetch` fetches the elements of the queue `prefetchCache_` in order, but the order in which these threads call `Stream.next` is not guaranteed. `OrderedPrefetch` also fetches the elements of a vector `prefetchCache_` in order, but each package task enqueued in the `pool_` is assigned a single `idx` captured by the lambda, that points to an index in the underlying `buffer_`. A `std::lock_guard` is used to ensure atomicity of calls to `OrderedPrefetch .next`. 
Interestingly, the main limitation of this …
=> Add ordered_prefetch

.circleci/config.yml, mlx/data/Array.cpp, python/src/wrap.cpp, python/tests/test_buffer.py, super/CMakeLists.txt
Update our CI so it will actually build and run the minimal tests we have. In addition this
- Fixes the super build on the Mac and Linux (minor changes)
- Changes the way we cast to `Array`. Previously everything was cast to numpy and then made into an `Array` without copy. Basically, we relied on numpy to do the copy. We now
- copy buffers ourselves
- cast scalars directly
- refuse to cast strings if they are not converted to bytes
- delegate to numpy to handle the array interface which means we still get no copy arrays from PyTorch for instance
=> Update CI and minor fixes

CMakeLists.txt, mlx/data/Array.cpp, mlx/data/Array.h, mlx/data/Dataset.cpp, mlx/data/Dataset.h, mlx/data/core/Utils.cpp, mlx/data/core/Utils.h, mlx/data/op/Replace.cpp, mlx/data/op/Replace.h, python/src/wrap.cpp, python/src/wrap_dataset.h, python/tests/test_replace.py
Like the tests, it enables replacing array subsequences with other array subsequences. The resulting array is flattened regardless of the original number of dimensions. Although any type is supported, only int8 arrays are exposed for string replacement.
The subsequence search code is not optimal but it is pretty fast so we could optimize if it becomes a bottleneck.
=> Add a replace operation

.circleci/config.yml
Fix typo in build-release jobs in CI. They weren't checked before because they can only run on the main branch.
=> Fix typo in CI

.circleci/config.yml
Fixed another typo and removed the extra Xcode build since it isn't necessary to build with the latest Xcode. We aren't using anything specific to Mac OS 14+.
Ran a dev_release workflow to avoid having more typos.
=> Final CI fixes

CMakeLists.txt, mlx/data/Dataset.cpp, mlx/data/Dataset.h, mlx/data/core/BPETokenizer.cpp, mlx/data/core/BPETokenizer.h, mlx/data/core/Trie.h, mlx/data/op/Tokenize.cpp, mlx/data/op/Tokenize.h, python/mlx/data/tokenizer_helpers.py, python/src/wrap_core.cpp, python/src/wrap_dataset.h, python/tests/test_bpe.py
This PR is on top of #61 and I will rebase to simplify the diff once that is merged. Please ignore "replace" related code here.
The changes in this PR are to support an implementation of BPE tokenizers. It adds a bunch of functionality to the `Trie` and it also adds a `BPEMerges` data structure which is a thin wrapper on top of a map of maps. No backwards incompatible changes anywhere except `read_trie_from_spm` which now doesn't change the space character and results in closer tokenizations to SPM even when not using BPE.
- Most things are moved to work with iterators internally which removes a bunch of `std::vector<char>` creations and copies.
- Add `search_longest_prefix` which the `Trie` is perfect for
- Add the ability to set the `id` when inserting
- Changed the vector that holds …
=> Add BPE tokenizers

mlx/data/core/Graph.cpp
While trying to build `mlx-data` from source using Linux containers (e.g. `debian:trixie`), I noticed that compiler complains that `reverse_copy` is not a member of `std`.
This issue can be fixed by including the `<algorithm>` header in Graph.cpp.
```
[11%] Building CXX object CMakeFiles/mlxdata.dir/mlx/data/core/Graph.cpp.o
#36 10.59 /home/mpiuser/mlx-data/mlx/data/core/Graph.cpp: In member function 'std::tuple<std::vector<long int, std::allocator<long int> >, std::vector<long int, std::allocator<long int> > > mlx::data::core::ShortestPath::find(double*)':
#36 10.59 /home/mpiuser/mlx-data/mlx/data/core/Graph.cpp:228:14: error: 'reverse_copy' is not a member of 'std'
#36 10.59   228 |         std::reverse_copy(
#36 10.59       |              ^~~~~~~~~~~~
#36 10.59 …
```
=> fix(core): Include algorithm library in Graph

docs/src/python/common_datasets.rst, python/mlx/data/datasets/__init__.py, python/mlx/data/datasets/libritts_r.py
[LibriTTS-R](https://arxiv.org/abs/2305.18802) is a commonly used dataset in text-to-speech development, because it contains ~600 hours of clean audiobook-style audio and normalized transcriptions at 24kHz.
It and the original LibriTTS dataset it's derived from have about 800 citations according to Semantic Scholar, so I'm proposing we add it as a common-use dataset.
=> Add LibriTTS-R dataset
